### PR TITLE
fixed log function

### PR DESCRIPTION
**Pull request by reggi**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by reggi** [comment]
I signed the CLA :)

**Comment by marcelerz** [comment]
You are correct that this shouldn't be ```this``` - it is a bug. However, if the ```log``` method is moved to the prototype, then code that depends on the ```log``` method will break since it expects the method to be on the constructor instead of the prototype. I will close this PR and use ```PNGImage.log``` to call the ```log``` method. This will make sure that the behavior doesn't change and that the bugfix is backwards compatible. 
Thank you for submitting this bug report and PR.

If you are wondering why the log is on the constructor instead of the prototype: It is there to make it possible to listen-in on non-'instance' calls like ```loadImage``` that is defined on the constructor.

**Comment by reggi** [comment]
Very fascinating! Thanks for the detailed description @marcelerz!

**Pull request closed without merging**
